### ISSUE TITLE
Comments are not properly ignored when enforcing headers at the top

### ISSUE THREAD

**Issue by bettinaheim** [davidquinn/psi-header#50] opened 2023-02-14 19:56 UTC
The following configuration leads to existing headers not being properly detected:
```
    "psi-header.changes-tracking": {
        "isActive": true,
        "enforceHeader": true,
        "autoHeader": "autoSave",
        "include": ["python"]
    },
    "psi-header.lang-config": [
        {
            "language": "python",
            "forceToTop": true,
            "begin": "# === #",
            "prefix": "# ",
            "suffix": " #",
            "lineLength": 80,
            "end": "# === #",
            "ignoreLines": [] // or alternatively also when set to ["#"]
        },
    ]
```
causes another (ill-formatted) header to be inserted when there is already one present in the form of
```
# some comment

# === #
# <copyright header>
# === #
```

Extension version: v1.21.0
VS Code version: 1.75.1

**Comment by davidquinn** [comment] 2023-02-16 10:17
What is in the template?
At what point is this occurring - on initial save of a new file, or an existing file that has previously been saved?
Is the existing header at the top of the file?
Is the problem happening in in a python file or something else?

Regards
D

**Comment by davidquinn** [comment] 2023-02-17 19:29
It is difficult to help without more information, but I will try to guess what you might be doing. 

Are you saying that you have a python file that already includes the following text and that when you save that file it adds another header?

```
# some comment

# === #
# <copyright header>
# === #
```

If so, that is expected behaviour given your configuration because you have the `forceToTop` option set to `true` - so the extension expects the header to be _the first thing in the file_. However, you have the text `# some comment` that is not part of the header above the existing header - so your original header is no longer at the top of the file.

So you either need to turn `forceToTop` off or do not put other text before the header.

Also, in what way is the second header ill-formatted?

Regards
D

**Comment by bettinaheim** [comment] 2023-03-07 10:41
@davidquinn Sometimes there is a need to have certain commented out lines above the header. My understanding of the docs is that this is exactly what "ignoreLines" is for. However, that does not seem to work properly; Adding "#" to ignoreLines does not make it ignore these lines and recognize a header below them. Furthermore, the documentation of ignoreLines also seems to indicate that any commented out lines before the header should always be ignored. It seems therefore that this is not behavior according to design, and if it is, it would be nice to be able to force headers at the top but allow for comments above it.

**Comment by davidquinn** [comment] 2023-03-08 09:23
Thanks for the response. The documentation says that lines that *_start with_* the string(s) defined in `ignoreLines` will be ignored. The only thing it will automatically ignore without a valid `ignoreLines` configuration is blank lines.

In your original example, you have added the `ignoreLines` property with an empty array - so effectively you have told it to not ignore anything above the header.

From the comment on that line, you have also tried to configure it to ignore any line that starts with '#'. That will effectively ignore your header because every line of your header starts with '#'. That is why it adds a new header in that scenario.

So, you have to add one or more strings to `ignoreLines` to get it to ignore anything above the header *_and_* you have to make sure that the string(s) you put into `ignoreLines` include enough characters to make it find the correct lines - so in your example, something like the following would work:

```json
...
   "ignoreLines": ["# some"]
...
```

Why does it work this way? Because the extension does not know for sure where the header is - it just knows where it *_ought_* to be. So when you save a file, it starts reading the file line by line to try and work out where the header might be - using the configuration to help.

Regards
D

**Comment by bettinaheim** [comment] 2023-03-08 18:57
Got it. We can confirm that being mir explicit with what comment lines to ignore works.

**Comment by davidquinn** [comment] 2023-03-08 19:57
Great. Thanks for confirming. I will re-close this issue now

D

**Closed** 2023-03-08 19:58 UTC
